### PR TITLE
Feature/support width height

### LINKED ISSUE #18: Detect `width` and `height`
Thank you for developing useful plugin! 😍

---

`width` and `height` are not warned by this plugin.

We should use `block-size` instead of `height`,
and `inline-size` instead of `width`

See:
https://developer.mozilla.org/en-US/docs/Web/CSS/block-size
https://developer.mozilla.org/en-US/docs/Web/CSS/inline-size

### PR DESCRIPTION
**Pull request by kagankan**
Fix #18 

Add support for width/height properties.

And fixed eslint errors, because I failed to commit.

### CODE REVIEW

**Comment by alexgwolff** [comment]
Any updates?

**Comment by alexgwolff** [comment]
@jonathantneal

**Comment by azat-io** [comment]
@jonathantneal Can you merge it?

**Comment by jonathantneal** [comment]
Whoa whoa, thanks for the ping, @azat-io, @alexgwolff ! And thanks for the PR, @kagankan!

**Comment by jonathantneal** [comment]
This has been published as v2.1.0. 🙏

**Pull request merged**
